{% set name = "libelfin" %}
{% set version = "0.3" %}
{% set sha256 = "c338942b967582922b3514b54b93175ca9051a9668db92dd8ef619824d443ac7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/aclements/libelfin/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-build-failure-with-llvm-10.patch  # [osx]
    - 0002-llvm-ld-has-no-soname-flag.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  script:
    - make DESTDIR="${PREFIX}" install

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/include/libelfin/elf/elf++.hh
    - test -f ${PREFIX}/include/libelfin/elf/data.hh
    - test -f ${PREFIX}/include/libelfin/elf/common.hh
    - test -f ${PREFIX}/include/libelfin/dwarf/dwarf++.hh
    - test -f ${PREFIX}/include/libelfin/dwarf/data.hh
    - test -f ${PREFIX}/include/libelfin/dwarf/small_vector.hh

about:
  home: https://github.com/aclements/libelfin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Libelfin is a from-scratch C++11 library for reading ELF binaries and DWARFv4 debug information.
  description: Libelfin is a from-scratch C++11 library for reading ELF binaries and DWARFv4 debug information. 
  dev_url: https://github.com/aclements/libelfin

extra:
  recipe-maintainers:
    - roeey777
